name: Build and Test

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
      - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional"
        
    - name: Restore NuGet packages
      run: nuget restore 'MET - Solution.sln'
      
    - name: Build solution
      run: msbuild YourSolution.sln /p:Configuration=Release
        