name: Build and Test

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Visual Studio 2022
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '2022'
        
    - name: Restore NuGet packages
      run: nuget restore 'MET - Solution.sln'
      
    - name: Build solution
      run: msbuild YourSolution.sln /p:Configuration=Release
        